version: '3.9'
services:
  db-node:
    container_name: db-node
    image: timescale/timescaledb-ha:pg16-ts2.14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ~/.cdcdbz/db-node:/var/lib/postgresql/data
      - ./init-files/init-postgis-db.sql:/docker-entrypoint-initdb.d/init-postgis-db.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"